# Generated by Django 3.2.5 on 2025-03-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary1',
            field=models.TextField(default='default', max_length=500),
            preserve_default=False,
        ),
    ]
