# Generated by Django 3.2.5 on 2025-03-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_summary1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary1',
        ),
    ]
